# UCI Image Segmentation Data 

#### https://archive.ics.uci.edu/ml/datasets/Image+Segmentation

Data description from https://archive.ics.uci.edu/ml/machine-learning-databases/image/segmentation.names:
1. Title: Image Segmentation data

2. Source Information
   -- Creators: Vision Group, University of Massachusetts
   -- Donor: Vision Group (Carla Brodley, brodley@cs.umass.edu)
   -- Date: November, 1990
 
3. Past Usage: None yet published

4. Relevant Information:

   The instances were drawn randomly from a database of 7 outdoor 
   images.  The images were handsegmented to create a classification
   for every pixel.  

   Each instance is a 3x3 region.

5. Number of Instances: Training data: 210  Test data: 2100

6. Number of Attributes: 19 continuous attributes

7. Attribute Information:

    1.  region-centroid-col:  the column of the center pixel of the region.
    2.  region-centroid-row:  the row of the center pixel of the region.
    3.  region-pixel-count:  the number of pixels in a region = 9.
    4.  short-line-density-5:  the results of a line extractoin algorithm that 
         counts how many lines of length 5 (any orientation) with
         low contrast, less than or equal to 5, go through the region.
    5.  short-line-density-2:  same as short-line-density-5 but counts lines
         of high contrast, greater than 5.
    6.  vedge-mean:  measure the contrast of horizontally
         adjacent pixels in the region.  There are 6, the mean and 
         standard deviation are given.  This attribute is used as
        a vertical edge detector.
    7.  vegde-sd:  (see 6)
    8.  hedge-mean:  measures the contrast of vertically adjacent
          pixels. Used for horizontal line detection. 
    9.  hedge-sd: (see 8).
    10. intensity-mean:  the average over the region of (R + G + B)/3
    11. rawred-mean: the average over the region of the R value.
    12. rawblue-mean: the average over the region of the B value.
    13. rawgreen-mean: the average over the region of the G value.
    14. exred-mean: measure the excess red:  (2R - (G + B))
    15. exblue-mean: measure the excess blue:  (2B - (G + R))
    16. exgreen-mean: measure the excess green:  (2G - (R + B))
    17. value-mean:  3-d nonlinear transformation
         of RGB. (Algorithm can be found in Foley and VanDam, Fundamentals
         of Interactive Computer Graphics)
    18. saturatoin-mean:  (see 17)
    19. hue-mean:  (see 17)

8. Missing Attribute Values: None

9. Class Distribution: 

   Classes:  brickface, sky, foliage, cement, window, path, grass.

   30 instances per class for training data.
   300 instances per class for test data.


In [72]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Test set and training set

The data has been separated into training set, with 210 instances (30 instances for each class) in the training set and with 2100 instances (300 instances for each class) in the test set.

In [73]:
train = pd.read_table('Source/segmentation.data',  sep=',', header=2, na_filter=True)
test = pd.read_table('Source/segmentation.test',  sep=',', header=2, na_filter=True)

In [74]:
train.shape

(210, 19)

In [75]:
test.shape

(2100, 19)

In [76]:
train.head()

REGION-CENTROID-COL  REGION-CENTROID-ROW  REGION-PIXEL-COUNT  \
BRICKFACE                  140                  125                   9   
BRICKFACE                  188                  133                   9   
BRICKFACE                  105                  139                   9   
BRICKFACE                   34                  137                   9   
BRICKFACE                   39                  111                   9   

           SHORT-LINE-DENSITY-5  SHORT-LINE-DENSITY-2  VEDGE-MEAN  VEDGE-SD  \
BRICKFACE                     0                     0    0.277778  0.062963   
BRICKFACE                     0                     0    0.333333  0.266667   
BRICKFACE                     0                     0    0.277778  0.107407   
BRICKFACE                     0                     0    0.500000  0.166667   
BRICKFACE                     0                     0    0.722222  0.374074   

           HEDGE-MEAN  HEDGE-SD  INTENSITY-MEAN  RAWRED-MEAN  RAWBLUE-MEAN  \
BRICKFACE    0.666667  0.311111        6.185185     7.333334      7.666666   
BRICKFACE    0.500000  0.077778        6.666666     8.333334      7.777778   
BRICKFACE    0.833333  0.522222        6.111111     7.555555      7.222222   
BRICKFACE    1.111111  0.474074        5.851852     7.777778      6.444445   
BRICKFACE    0.888889  0.429629        6.037037     7.000000      7.666666   

           RAWGREEN-MEAN  EXRED-MEAN  EXBLUE-MEAN  EXGREEN-MEAN  VALUE-MEAN  \
BRICKFACE       3.555556    3.444444     4.444445     -7.888889    7.777778   
BRICKFACE       3.888889    5.000000     3.333333     -8.333333    8.444445   
BRICKFACE       3.555556    4.333334     3.333333     -7.666666    7.555555   
BRICKFACE       3.333333    5.777778     1.777778     -7.555555    7.777778   
BRICKFACE       3.444444    2.888889     4.888889     -7.777778    7.888889   

           SATURATION-MEAN  HUE-MEAN  
BRICKFACE         0.545635 -1.121818  
BRICKFACE         0.538580 -0.924817  
BRICKFACE         0.532628 -0.965946  
BRICKFACE         0.573633 -0.744272  
BRICKFACE         0.562919 -1.175773

Index label column

In [77]:
train.index.name = 'label'
train.reset_index(inplace=True)

test.index.name = 'label'
test.reset_index(inplace=True)

Create array with labels for the test and training data. Drop the label column in the test and train arrays


In [78]:
train_label = train.label
train = train.drop('label', 1)

test_label = test.label
test = test.drop('label', 1)

label = np.unique(test_label)
print label

['BRICKFACE' 'CEMENT' 'FOLIAGE' 'GRASS' 'PATH' 'SKY' 'WINDOW']


### Random Forest Classifier

In [79]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf = clf.fit(train, train_label)

#### Accuracy score

In [80]:
from sklearn import metrics
pred = clf.predict(test)
accuracy = metrics.accuracy_score(test_label, pred)
print "Accuracy:{0:.3f}".format(accuracy)

Accuracy:0.947


#### Classification report

In [81]:
print "Classification report"
print metrics.classification_report(test_label, pred)

Classification report
             precision    recall  f1-score   support

  BRICKFACE       0.97      0.99      0.98       300
     CEMENT       0.90      0.94      0.92       300
    FOLIAGE       0.89      0.90      0.90       300
      GRASS       1.00      0.99      0.99       300
       PATH       0.98      0.99      0.99       300
        SKY       1.00      1.00      1.00       300
     WINDOW       0.88      0.82      0.85       300

avg / total       0.95      0.95      0.95      2100



#### Confusion Matrix

In [69]:
print "Confusion Matrix"
print metrics.confusion_matrix(test_label, pred)

Confusion Matrix
[[289   3   1   0   0   0   7]
 [  1 268   2   1   0   0  28]
 [  2   6 265   0   0   1  26]
 [  0   0   0 299   0   0   1]
 [  0   0   1   1 298   0   0]
 [  0   0   0   0   0 300   0]
 [  3   8  39   0   0   0 250]]
